// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"wire/foobarbaz"
)

// Injectors from wrie.go:

func InitMission(name string) foobarbaz.Mission {
	player := foobarbaz.NewPlayer(name)
	monster := foobarbaz.NewMonster()
	mission := foobarbaz.NewMission(player, monster)
	return mission
}

func main() {
	mission := InitMission("dj")

	mission.Start()
}
